### ISSUE TITLE
CrawlDirUtils failing tests

### ISSUE THREAD

**Issue by bernardosgr** [bixo/bixo#65]
Hi guys, I'm trying to build the project, to start doing some fancy things but I'm having a hard time doing it because some test id failing. Is there a way to understand the root of the problem?

<code>C:\Users\Bernardo\Desktop\TESE\Bixo>ant clean test
Buildfile: C:\Users\Bernardo\Desktop\TESE\Bixo\build.xml

clean:
     [echo] cleaning bixo-core

mvn-init:
     [echo] maven.repo.local=C:\Users\Bernardo/.m2/repository

compile:
    [mkdir] Created dir: C:\Users\Bernardo\Desktop\TESE\Bixo\build\classes-main
    [javac] Compiling 95 source files to C:\Users\Bernardo\Desktop\TESE\Bixo\bui
ld\classes-main
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: C:\Users\Bernardo\Desktop\TESE\Bixo\src\main\java\bixo\utils\D
iskQueue.java uses unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.

compile-test:
     [echo] *** Building Unit Tests Sources ***
    [mkdir] Created dir: C:\Users\Bernardo\Desktop\TESE\Bixo\build\classes-test
    [javac] Compiling 54 source files to C:\Users\Bernardo\Desktop\TESE\Bixo\bui
ld\classes-test
    [javac] Note: C:\Users\Bernardo\Desktop\TESE\Bixo\src\test\java\bixo\fetcher
\SimpleHttpFetcherTest.java uses or overrides a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.

test:
    [mkdir] Created dir: C:\Users\Bernardo\Desktop\TESE\Bixo\build\test
    [junit] WARNING: multiple versions of ant detected in path for junit
    [junit]          jar:file:/C:/ant/lib/ant.jar!/org/apache/tools/ant/Project.
class
    [junit]      and jar:file:/C:/Users/Bernardo/.m2/repository/org/apache/ant/a
nt/1.8.4/ant-1.8.4.jar!/org/apache/tools/ant/Project.class
    [junit] Running bixo.config.AdaptiveFetcherPolicyTest
    [junit] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0,02
2 sec
    [junit] Running bixo.config.DefaultFetchJobPolicyTest
    [junit] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0,12
9 sec
    [junit] Running bixo.config.FakeUserFetcherPolicyTest
    [junit] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0,07
 sec
    [junit] Running bixo.config.FetcherPolicyTest
    [junit] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0,01
9 sec
    [junit] Running bixo.datum.FetchSetDatumTest
    [junit] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0,16
5 sec
    [junit] Running bixo.datum.FetchedDatumTest
    [junit] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0,13
5 sec
    [junit] Running bixo.datum.HttpHeadersTest
    [junit] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0,12
3 sec
    [junit] Running bixo.datum.OutlinkTest
    [junit] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0,01
7 sec
    [junit] Running bixo.datum.ScoredUrlDatumTest
    [junit] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0,62
9 sec
    [junit] Running bixo.datum.StatusDatumTest
    [junit] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0,12
4 sec
    [junit] Running bixo.exceptions.BaseFetchExceptionTest
    [junit] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0,03
4 sec
    [junit] Running bixo.exceptions.HttpFetchExceptionTest
    [junit] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0,11
1 sec
    [junit] Running bixo.exceptions.RedirectFetchExceptionTest
    [junit] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0,03
9 sec
    [junit] Running bixo.fetcher.SimpleHttpFetcherTest
    [junit] Tests run: 18, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 29,
39 sec
    [junit] Running bixo.fetcher.simulation.WebgraphWebServerTest
    [junit] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0,01
9 sec
    [junit] Running bixo.fetcher.test.HandlerTest
    [junit] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0,36
3 sec
    [junit] Running bixo.operations.FilterAndScoreByUrlAndRobotsTest
    [junit] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 5,84
1 sec
    [junit] Running bixo.operations.FixedScoreGeneratorTest
    [junit] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0,01
7 sec
    [junit] Running bixo.parser.SimpleParserTest
    [junit] Tests run: 16, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1,1
05 sec
    [junit] Running bixo.parser.TikaCallableTest
    [junit] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1,48
 sec
    [junit] Running bixo.pipes.FetchPipeLocalTest
    [junit] Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 30,7
9 sec
    [junit] Running bixo.pipes.ParsePipeTest
    [junit] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4,24
 sec
    [junit] Running bixo.robots.RobotUtilsTest
    [junit] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0,9
sec
    [junit] Running bixo.robots.SimpleRobotRulesParserTest
    [junit] Tests run: 33, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0,1
98 sec
    [junit] Running bixo.urls.SimpleUrlFilterTest
    [junit] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0,12
9 sec
    [junit] Running bixo.urls.SimpleUrlNormalizerTest
    [junit] Tests run: 13, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0,1
33 sec
    [junit] Running bixo.urls.SimpleUrlValidatorTest
    [junit] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0,04
9 sec
    [junit] Running bixo.utils.CrawlDirUtilsTest
    [junit] Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0,15
8 sec
    [junit] Test bixo.utils.CrawlDirUtilsTest FAILED
    [junit] Running bixo.utils.DiskQueueTest
    [junit] Tests run: 13, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1,6
59 sec
    [junit] Running bixo.utils.DomainInfoTest
    [junit] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0,02
1 sec
    [junit] Running bixo.utils.DomainNamesTest
    [junit] Tests run: 14, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0,0
27 sec
    [junit] Running bixo.utils.EncodingUtilsTest
    [junit] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0,10
1 sec
    [junit] Running bixo.utils.GroupingKeyTest
    [junit] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0,02
2 sec
    [junit] Running bixo.utils.HtmlUtilsTest
    [junit] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0,02
3 sec
    [junit] Running bixo.utils.HttpUtilsTest
    [junit] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0,02
3 sec
    [junit] Running bixo.utils.StringUtilsTest
    [junit] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0,01
7 sec
    [junit] Running bixo.utils.ThreadedExecutorTest
    [junit] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0,36
9 sec
    [junit] Running bixo.utils.UrlUtilsTest
    [junit] Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0,11
3 sec

BUILD FAILED
C:\Users\Bernardo\Desktop\TESE\Bixo\build.xml:187: Tests failed!

Total time: 1 minute 49 seconds
</code>

**Comment by bixo** [comment]
Hi Bernardo,

It looks like this test is failing:

[junit] Running bixo.utils.CrawlDirUtilsTest
[junit] Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0,15

If you look inside of the build/ sub-dir, there should be a file called something like TEST-bixo.utils.CrawlDirUtilsTest.txt, and that will have details of what exactly failed.

Also, I see you're building on Windows. In general doing Hadoop-related dev on Windows requires the use fo Cygwin, though more recent releases of Hadoop can be made to work with the installation of various DLLs.

-- Ken

> 
> From: Bernardo Rodrigues
> Sent: January 4, 2015 5:01:51am PST
> To: bixo/bixo
> Subject: [bixo] CrawlDirUtils failing tests (#65)
> 
> Hi guys, I'm trying to build the project, to start doing some fancy things but I'm having a hard time doing it because some test id failing. Is there a way to understand the root of the problem?
> 
> C:\Users\Bernardo\Desktop\TESE\Bixo>ant clean test
> Buildfile: C:\Users\Bernardo\Desktop\TESE\Bixo\build.xml
> 
> clean:
> [echo] cleaning bixo-core
> 
> mvn-init:
> [echo] maven.repo.local=C:\Users\Bernardo/.m2/repository
> 
> compile:
> [mkdir] Created dir: C:\Users\Bernardo\Desktop\TESE\Bixo\build\classes-main
> [javac] Compiling 95 source files to C:\Users\Bernardo\Desktop\TESE\Bixo\bui
> ld\classes-main
> [javac] Note: Some input files use or override a deprecated API.
> [javac] Note: Recompile with -Xlint:deprecation for details.
> [javac] Note: C:\Users\Bernardo\Desktop\TESE\Bixo\src\main\java\bixo\utils\D
> iskQueue.java uses unchecked or unsafe operations.
> [javac] Note: Recompile with -Xlint:unchecked for details.
> 
> compile-test:
> [echo] *** Building Unit Tests Sources ***
> [mkdir] Created dir: C:\Users\Bernardo\Desktop\TESE\Bixo\build\classes-test
> [javac] Compiling 54 source files to C:\Users\Bernardo\Desktop\TESE\Bixo\bui
> ld\classes-test
> [javac] Note: C:\Users\Bernardo\Desktop\TESE\Bixo\src\test\java\bixo\fetcher
> \SimpleHttpFetcherTest.java uses or overrides a deprecated API.
> [javac] Note: Recompile with -Xlint:deprecation for details.
> 
> test:
> [mkdir] Created dir: C:\Users\Bernardo\Desktop\TESE\Bixo\build\test
> [junit] WARNING: multiple versions of ant detected in path for junit
> [junit] jar:file:/C:/ant/lib/ant.jar!/org/apache/tools/ant/Project.
> class
> [junit] and jar:file:/C:/Users/Bernardo/.m2/repository/org/apache/ant/a
> nt/1.8.4/ant-1.8.4.jar!/org/apache/tools/ant/Project.class
> [junit] Running bixo.config.AdaptiveFetcherPolicyTest
> [junit] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0,02
> 2 sec
> [junit] Running bixo.config.DefaultFetchJobPolicyTest
> [junit] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0,12
> 9 sec
> [junit] Running bixo.config.FakeUserFetcherPolicyTest
> [junit] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0,07
> sec
> [junit] Running bixo.config.FetcherPolicyTest
> [junit] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0,01
> 9 sec
> [junit] Running bixo.datum.FetchSetDatumTest
> [junit] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0,16
> 5 sec
> [junit] Running bixo.datum.FetchedDatumTest
> [junit] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0,13
> 5 sec
> [junit] Running bixo.datum.HttpHeadersTest
> [junit] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0,12
> 3 sec
> [junit] Running bixo.datum.OutlinkTest
> [junit] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0,01
> 7 sec
> [junit] Running bixo.datum.ScoredUrlDatumTest
> [junit] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0,62
> 9 sec
> [junit] Running bixo.datum.StatusDatumTest
> [junit] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0,12
> 4 sec
> [junit] Running bixo.exceptions.BaseFetchExceptionTest
> [junit] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0,03
> 4 sec
> [junit] Running bixo.exceptions.HttpFetchExceptionTest
> [junit] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0,11
> 1 sec
> [junit] Running bixo.exceptions.RedirectFetchExceptionTest
> [junit] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0,03
> 9 sec
> [junit] Running bixo.fetcher.SimpleHttpFetcherTest
> [junit] Tests run: 18, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 29,
> 39 sec
> [junit] Running bixo.fetcher.simulation.WebgraphWebServerTest
> [junit] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0,01
> 9 sec
> [junit] Running bixo.fetcher.test.HandlerTest
> [junit] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0,36
> 3 sec
> [junit] Running bixo.operations.FilterAndScoreByUrlAndRobotsTest
> [junit] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 5,84
> 1 sec
> [junit] Running bixo.operations.FixedScoreGeneratorTest
> [junit] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0,01
> 7 sec
> [junit] Running bixo.parser.SimpleParserTest
> [junit] Tests run: 16, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1,1
> 05 sec
> [junit] Running bixo.parser.TikaCallableTest
> [junit] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1,48
> sec
> [junit] Running bixo.pipes.FetchPipeLocalTest
> [junit] Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 30,7
> 9 sec
> [junit] Running bixo.pipes.ParsePipeTest
> [junit] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4,24
> sec
> [junit] Running bixo.robots.RobotUtilsTest
> [junit] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0,9
> sec
> [junit] Running bixo.robots.SimpleRobotRulesParserTest
> [junit] Tests run: 33, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0,1
> 98 sec
> [junit] Running bixo.urls.SimpleUrlFilterTest
> [junit] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0,12
> 9 sec
> [junit] Running bixo.urls.SimpleUrlNormalizerTest
> [junit] Tests run: 13, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0,1
> 33 sec
> [junit] Running bixo.urls.SimpleUrlValidatorTest
> [junit] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0,04
> 9 sec
> [junit] Running bixo.utils.CrawlDirUtilsTest
> [junit] Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0,15
> 8 sec
> [junit] Test bixo.utils.CrawlDirUtilsTest FAILED
> [junit] Running bixo.utils.DiskQueueTest
> [junit] Tests run: 13, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1,6
> 59 sec
> [junit] Running bixo.utils.DomainInfoTest
> [junit] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0,02
> 1 sec
> [junit] Running bixo.utils.DomainNamesTest
> [junit] Tests run: 14, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0,0
> 27 sec
> [junit] Running bixo.utils.EncodingUtilsTest
> [junit] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0,10
> 1 sec
> [junit] Running bixo.utils.GroupingKeyTest
> [junit] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0,02
> 2 sec
> [junit] Running bixo.utils.HtmlUtilsTest
> [junit] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0,02
> 3 sec
> [junit] Running bixo.utils.HttpUtilsTest
> [junit] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0,02
> 3 sec
> [junit] Running bixo.utils.StringUtilsTest
> [junit] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0,01
> 7 sec
> [junit] Running bixo.utils.ThreadedExecutorTest
> [junit] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0,36
> 9 sec
> [junit] Running bixo.utils.UrlUtilsTest
> [junit] Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0,11
> 3 sec
> 
> BUILD FAILED
> C:\Users\Bernardo\Desktop\TESE\Bixo\build.xml:187: Tests failed!
> 
> Total time: 1 minute 49 seconds
> —
> Reply to this email directly or view it on GitHub.
> 

--------------------------
Ken Krugler
+1 530-210-6378
http://www.scaleunlimited.com
custom big data solutions & training
Hadoop, Cascading, Cassandra & Solr

**Comment by bernardosgr** [comment]
Hi there, thanks for the help, good tip ;)
I'm able to see what caused the error now, but can't understand it:

Testsuite: bixo.utils.CrawlDirUtilsTest
Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0,158 sec

Testcase: testMakeLoopDir took 0,108 sec
	FAILED
null
junit.framework.AssertionFailedError: null
	at bixo.utils.CrawlDirUtilsTest.testMakeLoopDir(CrawlDirUtilsTest.java:54)

Testcase: testExtractLoopNumber took 0,008 sec
Testcase: testFindAllSubdirs took 0,003 sec
Testcase: testFindNextLoopDir took 0,011 sec
Testcase: testFindLatestLoopDir took 0,005 sec

However, when I try to do it in cygwin I get a different error:

$ ant clean test
Buildfile: C:\Users\Bernardo\Desktop\TESE\Bixo\build.xml

clean:
     [echo] cleaning bixo-core

mvn-init:
     [echo] maven.repo.local=C:\Users\Bernardo/.m2/repository

compile:
    [mkdir] Created dir: C:\Users\Bernardo\Desktop\TESE\Bixo\build\classes-main
    [javac] Compiling 95 source files to C:\Users\Bernardo\Desktop\TESE\Bixo\build\classes-main
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: C:\Users\Bernardo\Desktop\TESE\Bixo\src\main\java\bixo\utils\DiskQueue.java uses unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.

compile-test:
     [echo] *** Building Unit Tests Sources ***
    [mkdir] Created dir: C:\Users\Bernardo\Desktop\TESE\Bixo\build\classes-test
    [javac] Compiling 54 source files to C:\Users\Bernardo\Desktop\TESE\Bixo\build\classes-test
    [javac] Note: C:\Users\Bernardo\Desktop\TESE\Bixo\src\test\java\bixo\fetcher\SimpleHttpFetcherTest.java uses or overrides a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.

test:
   [delete] Deleting directory C:\Users\Bernardo\Desktop\TESE\Bixo\build\test

BUILD FAILED
C:\Users\Bernardo\Desktop\TESE\Bixo\build.xml:145: Unable to delete directory C:\Users\Bernardo\Desktop\TESE\Bixo\build\test

Total time: 28 seconds

**Comment by kkrugler** [comment]
Were you ever able to get past this error? I know that sometimes Cygwin has directory permission issues, but since I'm on a Mac I don't know how best to resolve them.

**Comment by hiidemo** [comment]
I got also this error when trying to build bixo project.
I use Windows 7 32 bit, and installed Apache Ant, Maven with lastest release
Pls help me!
This is error log:
Testcase: testMakeLoopDir took 0.151 sec
	FAILED
null
junit.framework.AssertionFailedError: null
	at bixo.utils.CrawlDirUtilsTest.testMakeLoopDir(CrawlDirUtilsTest.java:54)

**Comment by kkrugler** [comment]
Normally there's a file called something like "<name of class being tested>-TEST.txt" in the build/test output directory.

Please post the contents of that from the testMakeLoopDir test that failed.

As a side note, since Bixo uses Hadoop it's challenging to build on top of native Windows. Normally you'd need to install Cygwin and use that to build it.

Thanks,

-- Ken

> From: hiidemo
> Sent: April 21, 2015 2:54:50am PDT
> To: bixo/bixo
> Cc: Ken Krugler
> Subject: Re: [bixo] CrawlDirUtils failing tests (#65)
> 
> I got also this error when trying to build bixo project.
> I use Windows 7 32 bit, and installed Apache Ant, Maven with lastest release
> Pls help me!
> This is error log:
> Testcase: testMakeLoopDir took 0.151 sec
> FAILED
> null
> junit.framework.AssertionFailedError: null
> at bixo.utils.CrawlDirUtilsTest.testMakeLoopDir(CrawlDirUtilsTest.java:54)
> 
> —
> Reply to this email directly or view it on GitHub.
> 

--------------------------
Ken Krugler
+1 530-210-6378
http://www.scaleunlimited.com
custom big data solutions & training
Hadoop, Cascading, Cassandra & Solr





--------------------------
Ken Krugler
+1 530-210-6378
http://www.scaleunlimited.com
custom big data solutions & training
Hadoop, Cascading, Cassandra & Solr
